# Generated by Django 5.2.8 on 2026-02-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepe_user', '0002_alter_recipe_description_alter_recipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
