# Generated by Django 5.2.8 on 2026-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepe_user', '0003_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
