# Generated by Django 6.0.2 on 2026-02-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepe_user', '0006_department_studentid_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='student_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='department',
            name='student_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='department',
            name='student_email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='student_id',
            field=models.OneToOneField(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='reciepe_user.studentid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            field=models.CharField(default=12, max_length=100),
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
